twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

when@test:
    twig:
        strict_variables: true
